            # Methods
# Changing Function
newname="shravana".upper()
print('"shravana".upper()=',newname)
changename=newname.lower()
print("newname.lower()=",changename)
print("'Yes do it now'.title()=",'Yes do it now'.title())
print('"I love you".capitalize()=',"i love you".capitalize())
# Chaking Function
print("'#23?'.isalpha()",'#23?'.isalpha())
print("'india12'.isalpha()=",'india12'.isalpha())
print('"123".isdigit()=',"123".isdigit())
print('"indrani".isdigit()=',"indrani".isdigit())
print('"hi girls".isspace()=',"hi girls".isspace())
print('"    ".isspace()=',"   ".isspace())
print('"i love my job".isalnum()=',"i love my job".isalnum())
print('"India123".isalnum()=',"India123".isalnum())
print('len("indrani")=',len("indrani"))
# Keyboard ordinal number or ascci value
print("ord('A')=",ord('A'))
print("ord('a')=",ord('a'))
print("chr(66)=",chr(66))
print("chr(98)=",chr(98))
# Searching Function
word="pranaam"
print('"pranaam".find("na")=',"pranaam".find("na"))
print('"pranaam".find("na",4)=',"pranaam".find("na",4))
print('"pranaam".find("Na")=',"pranaam".find("Na"))
print('"pranaam".index("na")=',"pranaam".index("na"))
#print('"pranaam".index("na",4)=',"pranaam".index("na",4))
print('"coconut".count("co")=',"coconut".count("co"))
print('"coconut".count("co",2)=',"coconut".count("co",2))
print('"coconut".count("co",1,3)=',"coconut".count("co",1,3))
print('"coconut milk".partition("nut")=',"coconut milk".partition("nut"))
print('"coconut".partition("but")=',"coconut".partition("but"))
print('"Hi ".join("Five")=',"Hi ".join("Five "))
print('"coconut".rstrip("rst")=',"coconut".rstrip("rst"))
print('"   coconut   ".rstrip()=',"   coconut   ".rstrip())
print('"   coconut   ".lstrip()=',"   coconut   ".lstrip())
print('"coconut".lstrip("rcst")=',"rcstoconut".lstrip("rcst"))
print('"IndraNI Kundu".swapcase()=',"IndraNI Kundu".swapcase())
print("I am a computer teacher".split())
